/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERC20GodMode } from "./ERC20GodMode";
export type { ERC20Normalizer } from "./ERC20Normalizer";
export type { ERC20Permit } from "./ERC20Permit";
export type { ERC20Recover } from "./ERC20Recover";
export type { IERC20 } from "./IERC20";
export type { IERC20Normalizer } from "./IERC20Normalizer";
export type { IERC20Permit } from "./IERC20Permit";
export type { IERC20Recover } from "./IERC20Recover";
export type { NonStandardERC20 } from "./NonStandardERC20";
